# Generated by Django 3.2.5 on 2023-01-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user_name',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
