# Generated by Django 3.2.5 on 2023-01-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_author_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
