# Generated by Django 5.2.17 on 2026-09-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user_name',
            field=models.CharField(default='user', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog_app.category'),
        ),
    ]
