# Generated by Django 6.1.1 on 2026-09-22 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_note_trash'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='blog_app.post')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
