# Generated by Django 6.1.1 on 2026-09-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_personal_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
