# Generated by Django 5.2.17 on 2026-09-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_restore_truncated_author_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAttempt',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
