# Generated by Django 5.2.17 on 2026-09-22 07:55

from itertools import islice

from django.db import migrations, models

from blog_app.text import search_document


def populate_search_text(apps, schema_editor):
    Post = apps.get_model("blog_app", "Post")
    posts = Post.objects.using(schema_editor.connection.alias)
    # Bound memory use while backfilling existing notes; leave their content unchanged.
    rows = posts.only("pk", "title", "content").iterator(chunk_size=500)
    while batch := list(islice(rows, 500)):
        for post in batch:
            post.search_text = search_document(post.title, post.content)
        posts.bulk_update(batch, ["search_text"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_authattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_text',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.RunPython(populate_search_text, migrations.RunPython.noop),
    ]
